AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Tag:
    Type: String
    Description: Tag of the Docker Image.
    Default: TAG
  ECSClusterName:
    Type: String
    Description: Name of an existing ECS Cluster.
    Default: ECS_CLUSTER_NAME

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: aws-sushi
      ContainerDefinitions:
      - Name: sushi
        Cpu: '10'
        Essential: 'true'
        Image:
          "Fn::Sub":
            - '${AccountId}.dkr.ecr.${Region}.amazonaws.com/aws-sushi:TAG'
            - { AccountId: { "Ref" : "AWS::AccountId" }, Region: { "Ref" : "AWS::Region" }}
        Memory: '128'
        PortMappings:
        - ContainerPort: 80
          HostPort: 80
      Volumes:
      - Name: my-vol
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: ECS_CLUSTER_NAME
      DesiredCount: '1'
      TaskDefinition:
        Ref: TaskDefinition
Outputs:
  ecsservice:
    Value:
      Ref: Service
